let services = [
    {
        id: 1,
        title: "دندان پزشکی اطفال",
        titleEn: "Pediatric Dentistry",
        description: "امروزه اهمیت مراقبت از دندان‌ در سنین کودکی بر کسی پوشیده نیست. دندان کودکان نیز احتیاج به رسیدگی دارد. یک تا هفت سالگی زمانی است که کودکان دندان در می‌آورند و کم کم دندان‌های شیری از هفت سالگی شروع به افتادن می‌کنند.  در همین زمان، به کمک دندان پزشک متخصص اطفال، می‌توان کارهای درمانی دندان کودک را آغاز کرد. دندان پزشکی اطفال در کلینیک سعادت آباد، در محیطی آرام و جذاب انجام می‌شود تا کودک به راحتی بتواند خود را به پزشک بسپارد. رفتار با کودکان نیاز به توانایی و شناخت خاصی دارد. پزشکان متخصص کلینیک ما به دلیل تجربه کافی، می‌توانند با کودکان شما ارتباط بر قرار کرده و خدمات دندان پزشکی آن‌ها را به بهترین شکل انجام دهند.",
        descriptionEn: "Today, the importance of dental care in childhood is not hidden from anyone. Children's teeth also need care. One to seven years old is when children start teething, and baby teeth start to fall out from the age of seven.At the same time, with the help of a pediatric dentist, you can start treating the child's teeth. Pediatric dentistry in Saadat Abad clinic is performed in a calm and attractive environment so that the child can easily entrust himself to the doctor. Dealing with children requires special ability and knowledge. The specialist doctors of our clinic can communicate with your children and provide them with dental services in the best way due to their sufficient experience.",
    },
    {
        id: 2,
        title: "لمینت دندان",
        titleEn: "Dental Laminate",
        description: "بخش مهمی از زیبایی چهره، به دندان‌ها بر می‌گردد. برای زیبایی دندان‌ها روش‌های مختلفی وجود دارد که یکی از آن‌ها، لمینت است. لمینت‌ یا ونیر، روکش نازکی از جنس سرامیک است که بر روی دندان‌ها قرار می‌گیرد تا ظاهر دندان‌ها را زیباتر کند. زمانی که روکش‌ها روی دندان قرار می‌گیرند، ایرادهای دندان را از بین می‌برد و ظاهری زیبا به دندان‌ها می‌بخشد. از لمینت برای برطرف کردن شکستگی، بد رنگی، ترک خوردگی و نافرمی دندان‌ها استفاده می‌شود. از لمینت می‌توان به جای ارتودنسی هم استفاده کرد. دندان پزشکان متخصص کلینیک سعادت‌آباد با به روزترین روش‌ها و استفاده از مواد و امکانات لازم، خدمات لمینت شما را انجام می‌دهند. پس از معاینه دندان‌هایتان توسط دندان پزشک،در صورت نیاز به لمینت، دندان‌هایتان قالب‌گیری شده و به شما نوبت داده می‌شود. زمان انجام خدمات لمینت در کلینیک ما ۴ الی ۵ ساعته انجام می‌شود. پزشکان ما در طول روز تنها برای یک مراجع خدمات ارائه می‌دهند زیرا کیفیت برای ما بسیار اهمیت دارد. شما می‌توانید در محیطی کاملا بهداشتی و تحت نظر بهترین دندان پزشکان، دندان‌های خود را لمینت کنید. ما از زمان چک آپ تا انجام کار کنارتان هستیم.",
        descriptionEn: "Teeth are an important part of facial beauty. There are various methods to beautify teeth, one of which is laminate. Laminate or cover is a thin coating of ceramic that is placed on the teeth to make the appearance of the teeth more beautiful. When the crowns are placed on the teeth, they eliminate the defects of the teeth and give the teeth a beautiful appearance. Laminate is used to repair broken, discolored, cracked and irregular teeth. Laminate can be used instead of orthodontics. The specialist dentists of Saadat Abad Clinic perform your laminate services with the most up-to-date methods and the use of necessary materials and facilities. After the dental examination by the dentist, if you need laminate, your teeth will be molded and you will be given an appointment. Laminate service time in our clinic is 4 to 5 hours. Our doctors only serve one patient per day because quality is very important to us. You can laminate your teeth in a completely hygienic environment under the supervision of the best dentists. We are with you from the time of check-up to the completion of the work.",
    },
    {
        id: 3,
        title:"کامپوزیت",
        titleEn: "Composite",
        description: "داشتن لبخندی زیبا برای تمامی افراد مهم است. گاهی دندان دچار مشکلاتی مانند شکستگی یا بد رنگی می‌شود که می‌تواند بسیار آزار دهنده باشد. امروزه روش‌های زیادی برای انجام کارهای زیبایی بر روی دندان‌ها وجود دارد. یکی از این روش‌ها کامپوزیت است. کامپوزیت، ماده‌ای خمیری شکل است که برای برطرف کردن نقص‌های دندان از آن استفاده می‌شود. کامپوزیت‌ها نیازی به قالب‌گیری ندارند. این مواد توسط دندانپزشک متخصص، روی دندان‌ها قرار می‌گیرد و به آن فرم داده می‌شود تا مشکلات دندان‌ها را بپوشاند. شما می‌توانید با مراجعه به کلینیک دندان پزشکی سعادت‌آباد، توسط پزشکان ما چک آپ شوید و در صورت نیاز، برای انجام خدمات نوبت بگیرید. خدمات کامپوزیت در هر روز، تنها برای یک نفر در کلینیک ما انجام می‌شود و ۴ الی ۵ ساعت زمان می‌برد.",
        descriptionEn: "Having a beautiful smile is important for everyone. Sometimes the tooth has problems such as broken or discolored, which can be very annoying. Today, there are many ways to do cosmetic work on teeth. One of these methods is composite. Composite is a paste material that is used to fix tooth defects. Composites do not need to be molded. These materials are placed on the teeth by a specialist dentist and given a shape to cover the problems of the teeth. You can visit Saadat Abad dental clinic, get checked up by our doctors and make an appointment for services if needed. Composite services are performed for only one person in our clinic every day and it takes 4-5 hours.",
    },
    {
        id: 4,
        title: "بلیچینگ دندان",
        titleEn: "Teeth Bleaching",
        description: "سفیدی دندان‌ها برای افراد بسیار مهم است و لبخند را زیباتر می‌کند. برای سفید کردن دندان‌ها می‌توان از روش بلیچینگ استفاده کرد که درمان موثری برای از بین بردن بد رنگی دندان‌ها است. برای انجام این کار ابتدا باید به دندان پزشک متخصص مراجعه کنید و پس از تشخیص او، می‌توانید دندان‌هایتان را بلیچینگ کنید. بلیچینگ کم عارضه‌ترین درمان برای سفید کردن دندان است. در کلینیک دندان پزشکی سعادت‌آباد بلیچینگ در یک جلسه یک ساعته انجام می‌شود اما انجام این کار باید تداوم داشته باشد تا نتیجه دهد. ادامه مراحل می‌تواند در خانه و توسط خودتان انجام شود اما در کلینیک و توسط دندانپزشک نیز می‌توانید بلیچینگ را ادامه دهید.",
        descriptionEn: "Teeth whiteness is very important for people and makes the smile more beautiful. To whiten teeth, you can use the bleaching method, which is an effective treatment to remove the bad color of teeth. To do this, you must first visit a specialist dentist and after his diagnosis, you can bleach your teeth. Bleaching is the least complicated treatment for teeth whitening. In Saadat Abad dental clinic, bleaching is done in one hour session, but doing this work must be continued in order to get results. The continuation of the procedures can be done at home by yourself, but you can also continue bleaching in the clinic and by the dentist.",
    },
    {
        id: 5,
        title: "ایمپلنت",
        titleEn: "Implant",
        description: "دندان‌ها می‌توانند به دلایل متعددی مانند کشیدن یا پیری از بین بروند. برای جایگزین کردن آن‌ها، ایمپلنت روش بسیار موثری خواهد بود. ایمپلنت، پایه‌ای از جنس تیتانیوم است که درون لثه یا استخوان قرار گرفته و دندان مصنوعی روی آن قرار می‌گیرد. ابتدا لازم است دندان‌هایتان توسط دندانپزشکان کلینیک ما چک شده و نوبت دهی شود تا برای مراحل بعدی به کلینیک مراجعه کنید. در کلینیک دندانپزشکی سعادت آباد، ایمپلنت یک ساعته انجام می‌شود. برای گرفتن وقت اولیه می‌توانید با شماره‌های ما در ارتباط باشید. ",
        descriptionEn: "Teeth can be lost for a number of reasons, such as pulling or aging. To replace them, the implant will be a very effective method. An implant is a base made of titanium that is placed inside the gum or bone and the artificial tooth is placed on it. First, it is necessary to have your teeth checked by the dentists of our clinic and make an appointment to visit the clinic for the next steps. In Saadat Abad dental clinic, one-hour implant is performed. You can contact our numbers to make an initial appointment.",
    },
    {
        id: 6,
        title: "عصب کشی دندان",
        titleEn: "Root Canal",
        description: "عصب کشی، درمانی برای ریشه دندان است. این روش به جای کشیدن دندان استفاده می‌شود. زمانی که دندان دچار پوسیدگی یا عفونت می‌شود، دندان‌پزشک بخش داخلی دندان که پالپ نام دارد را از عفونت خالی کرده و جای آن را با مواد مخصوصی پر می‌کند. دندان‌پزشک متخصص کلینیک سعادت آباد، پس از معاینه دندان شما، در صورت لزوم، دندان شما را عصب کشی می‌کند که مدت زمان انجام این کار یک ساعت خواهد بود.",
        descriptionEn: "Nerve removal is a treatment for the root of the tooth. This method is used instead of tooth extraction. When the tooth is decayed or infected, the dentist removes the infection from the inner part of the tooth called the pulp and fills its place with special materials. The specialist dentist of Saadat Abad Clinic, after examining your teeth, if necessary, de-nerves your teeth, which will take one hour.",
    },
    {
        id: 7,
        title: "پروتز و روکش دندان",
        titleEn: "Prosthesis and Cover",
        description: "برای رفع مشکلات ظاهری دندان مانند شکستگی‌ها، پر کردن جاهای خالی و مواردی مانند آن از پروتز یا روکش دندان استفاده می‌شود. پروتز دندان از جمله خدمات زیبایی محسوب می‌شود که دارای دو نوع ثابت و متحرک است. در نوع ثابت، برای دندان‌هایی که آسیبی مانند شکستگی دارند از روکش استفاده می‌شود. پس از عصب کشی دندان نیز، برای استحکام آن از پروتز ثابت استفاده می‌کنند. پروتز متحرک، همان دندان‌های مصنوعی هستند که می‌توان آن‌ها را جا به جا کرد. پس از معاینه در کلینیک ندانپزشکی سعادت آباد، پزشک نوع روکش مناسب برای دندان شما را تشخیص داده و خدمات لازم برای دندان شما را آغاز می‌کند.",
        descriptionEn: "Prosthetics or dental veneers are used to solve the appearance problems of the teeth, such as fractures, filling empty spaces, and the like. Dental prosthesis is one of the beauty services that has two types, fixed and mobile. In the fixed type, veneers are used for teeth that have damage such as fractures. After denervation of the tooth, they use a fixed prosthesis for its strength. Removable dentures are artificial teeth that can be moved. After the examination at the Saadat Abad Dental Clinic, the doctor will determine the type of veneer suitable for your tooth and start the necessary services for your tooth.",
    },
    {
        id: 8,
        title: "ارتودنسی",
        titleEn: "Orthodontic",
        description: "گاهی دندان‌ها در جای مناسب خود قرار ندارند و بسیار نامرتب هستند. این امر تمیز نگه داشتن دندان‌ها را دشوار می‌کند و در نهایت باعث پوسیدگی آن‌ها می‌شود. ارتودنسی روشی مناسب برای درمان و زیبایی دندان‌هایی که به درستی کنار هم قرار نگرفته‌اند. تنها یک متخصص ارتودنسی می‌تواند تشخیص دهد که دندان شما به این خدمات احتیاج دارد یا خیر. لازم است ابتدا دندان‌پزشک متخصص ارتودنسی دندان‌های شما را معاینه کند، سپس در صورت نیاز برای انجام آن به شما نوبت داده می‌شود. از ارتودنسی برای رفع ناهنجاری‌های فک نیز استفاده می‌شود. ارتودنسی در دو نوع ثابت و متحرک انجام می‌شود و می‌تواند به صورت نامرئی، هم رنگ دندان یا پشت دندان‌ها قرار بگیرد تا مشخص نباشد. برای انجام خدمات ارتودنسی در کلینیک دندانپزشکی سعادت آباد می‌توانید از طریق راه‌های ارتباطی با ما در تماس باشید.",
        descriptionEn: "Sometimes the teeth are not in their proper place and are very messy. This makes it difficult to keep the teeth clean and eventually causes them to decay. Orthodontics is a suitable method to treat and beautify teeth that are not properly aligned. Only an orthodontist can determine if your tooth needs these services or not. It is necessary to first examine your teeth with an orthodontist, then if necessary, you will be given an appointment to do it. Orthodontics is also used to correct jaw abnormalities. Orthodontics is performed in two types, fixed and mobile, and can be invisible, the same color as the teeth, or behind the teeth so that it is not visible. To perform orthodontic services at Saadat Abad Dental Clinic, you can contact us through communication channels.",
    },
    {
        id: 9,
        title: "جراحی لثه",
        titleEn: "Gum Surgery",
        description: "لثه به دلایل مختلفی می‌تواند نیاز به جراحی داشته باشد. گاهی ممکن است لثه عفونت کند یا دچار کیست و تومور شود. مصرف برخی داروها، بیماری‌های عفونی و جمع شدن باکتری و پلاک در اطراف دندان‌ها و لثه از جمله دلایلی هستند که نیاز به جراحی دارند. بیماری‌هایی مانند گینوییت و پریودنتیت نیز به جراحی نیاز دارند. زمانی که لثه شما به هر دلیلی دچار مشکل شد، باید به دندانپزشک متخصص مراجعه کرده و مراحل درمان را آغاز کنید.همچنین جراحی لثه برای افزایش تاج دندان نیز انجام می‌شود که جنبه زیبایی دارد. تمامی جراحی‌های لثه در کلینیک دندانپزشکی سعادت آباد، تحت نظر باتجربه‌ترین دندانپزشکان انجام می‌شود. برای  گرفتن وقت معاینه می‌توانید با شماره‌های موجود در سایت تماس بگیرید.",
        descriptionEn: "Gums can require surgery for various reasons. Sometimes the gums may become infected or develop cysts and tumors. The use of certain drugs, infectious diseases, and the accumulation of bacteria and plaque around the teeth and gums are among the reasons that require surgery. Diseases such as gingivitis and periodontitis also require surgery. When your gums have a problem for any reason, you should visit a specialist dentist and start the treatment process. Gum surgery is also performed to increase the crown of the tooth, which has a cosmetic aspect. All gum surgeries in Saadat Abad dental clinic are performed under the supervision of the most experienced dentists. You can call the numbers on the website to make an appointment.",
    },
    {
        id: 10,
        title: "جراحی دهان و دندان",
        titleEn: "Oral Surgery",
        description: "خارج کردن دندان‌های نهفته، جراحی لثه و ایمپلنت از جمله جراحی‌های دهان و دندان محسوب می‌شوند. هر کدام از این خدمات، نیازمند پزشک متخصص هستند تا با تشخیص درست، بهترین خدمات درمانی را ارائه دهند. کلینیک دندانپزشکی سعادت آباد با داشتن دندانپزشکان متخصص همراه با امکانات کافی، سلامت دندان‌های شما را تضمین می‌کند.",
        descriptionEn: "Extraction of hidden teeth, gum surgery and implants are among oral and dental surgeries. Each of these services requires a specialist doctor to provide the best treatment services with a correct diagnosis. Saadat Abad dental clinic guarantees the health of your teeth by having expert dentists with sufficient facilities.",
    },
    {
        id: 11,
        title: "جراحی فرنکتومی",
        titleEn: "Frenectomy Surgery",
        description: "کودکان ممکن است با گره زبان یا لب که فرنوم نام دارد، متولد شوند. این گره‌ها در حرکت لب و زبان اختلال ایجاد می‌کنند و یا باعث پوسیدگی دندان می‌شوند. مشکلات گفتاری، فاصله بین دندان‌ها و مشکلات تنفسی و گوارشی از جمله مشکلاتی است که این گره‌ها به وجود می‌آورند. به همین دلیل باید برداشته شوند. فرایند برداشتن گره‌ها، جراحی فرنکتومی یا فرنوتومی نام دارد که توسط پزشک متخصص در کلینیک دندانپزشکی سعادت آباد انجام می‌شود. پس از معاینه و تشخیص پزشک، در صورت نیاز، مراحل جراحی فرنکتومی برای مراجعین انجام می‌شود.",
        descriptionEn: "Babies may be born with a tongue or lip knot called a frenum. These knots interfere with the movement of the lips and tongue or cause tooth decay. Speech problems, distance between teeth, and breathing and digestive problems are among the problems caused by these knots. That is why they should be removed. The process of removing nodes is called frenectomy or frenotomy, which is performed by a specialist doctor in Saadat Abad Dental Clinic. After the doctor's examination and diagnosis, if necessary, frenectomy procedures are performed for clients.",
    },
];

export default services;