import Head from "next/head";
import { useSelector } from "react-redux";
import Appointment from "../src/components/appointment/Appointment";
import Footer from "../src/components/footer/Footer";
import Header from "../src/components/header/Header";
import FullScreenLoader from "../src/tools/loader/FullScreenLoader";
import KarmaPn from "../src/tools/pn/KarmaPn";
import { BasicSection } from "../styles/globalStyleComponents";

export default function AppointmentPage() {
  const state = useSelector((state) => state.stateRegister);

  return (
    <div>
      <Head>
        <title>appointment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.userDataLoader && <FullScreenLoader />}
      <Header path={"Home"} />
      <main>
        <BasicSection footer={false}>
          <Appointment />
          <KarmaPn/>
        </BasicSection>
       
      </main>
    </div>
  );
}
