import Head from "next/head";
import Appointment from "../src/components/appointment/Appointment";
import Footer from "../src/components/footer/Footer";
import Header from "../src/components/header/Header";
import { BasicSection } from "../styles/globalStyleComponents";

export default function appointmentPage() {
  return (
    <div>
      <Head>
        <title>appointment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header path={"Home"} />
      <main>
        <BasicSection footer={true}>
          <Appointment />
        </BasicSection>
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
