import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/header/Header";
import Landing from "../src/components/landing/Landing";
import { BasicSection } from "../styles/globalStyleComponents";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Landing />
      </main>
    </div>
  );
}
