import Head from "next/head";
import Image from "next/image";
import { useTranslation } from "react-i18next";
import { useDispatch, useSelector } from "react-redux";
import Header from "../src/components/header/Header";
import Landing from "../src/components/landing/Landing";
import { hideVideo } from "../src/redux/video/videoActions";
import { BasicSection, VideoStyle } from "../styles/globalStyleComponents";
import DentistVidep from "../public/Assets/images/dentistVideo.mp4"
export default function Home() {
  const video = useSelector(state => state.stateVideo)
  const dispatch = useDispatch()
  const { t } = useTranslation()
  return (
    <div className={video.show && "sectionVideo"}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {

        video.show ?
          <VideoStyle>

            <video autoPlay playsInline muted preload="true" loop>
              <source
                src={DentistVidep}
                type="video/mp4"
                Accept-Ranges="bytes"
              />

              Your browser does not support the video tag.

            </video>
            <button onClick={() => dispatch(hideVideo())}>{t("skip")}</button>
          </VideoStyle>

          :
          <>
            <Header path={"Home"} />
            <main>
              <Landing />
            </main>
          </>
      }
    </div>
  );
}
